version: '3.9'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONDAY_API_TOKEN=${MONDAY_API_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=hubspot_monday
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: hubspot_monday
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
